### ISSUE TITLE
Quizzes don't complete

### ISSUE THREAD

**Issue by cal4** [klept0/MS-Rewards-Farmer#181]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Title

- [X] The title is no longer "Title" and I edited it with the right error name.

### Branch

develop

### Commit

8bc8ee9fbb578518255e53d0fb41456c4a57db74

### Describe the bug

bla

### Copy and paste your error

None

### Screenshots

bla

### Value of dashboard variable

bla

**Comment by cal4** [comment]
Fixed in #184

**Comment by ttraxxrepo** [comment]
Still having an issue with quiz

```
2024-08-20 00:11:28 2024-08-20 00:11:28 [INFO] [root] [dailySet.py:29] [DAILY SET] Completing search of card 1
2024-08-20 00:11:50 2024-08-20 00:11:50 [INFO] [root] [dailySet.py:46] [DAILY SET] Completing quiz of card 2
2024-08-20 00:12:00 2024-08-20 00:12:00 [ERROR] [root] [dailySet.py:84] [DAILY SET] Error Daily Set of card 2
2024-08-20 00:12:00 Traceback (most recent call last):
2024-08-20 00:12:00   File "/msrewards/src/dailySet.py", line 48, in completeDailySet
2024-08-20 00:12:00     self.activities.completeQuiz()
2024-08-20 00:12:00   File "/msrewards/src/activities.py", line 42, in completeQuiz
2024-08-20 00:12:00     startQuiz = self.browser.utils.waitUntilQuizLoads()
2024-08-20 00:12:00   File "/msrewards/src/utils.py", line 82, in waitUntilQuizLoads
2024-08-20 00:12:00     return self.waitUntilVisible(By.XPATH, '//*[@id="rqStartQuiz"]')
2024-08-20 00:12:00   File "/msrewards/src/utils.py", line 62, in waitUntilVisible
2024-08-20 00:12:00     return WebDriverWait(self.webdriver, timeToWait).until(
2024-08-20 00:12:00   File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.py", line 105, in until
2024-08-20 00:12:00     raise TimeoutException(message, screen, stacktrace)
2024-08-20 00:12:00 selenium.common.exceptions.TimeoutException: Message: 
2024-08-20 00:12:00 Stacktrace:
2024-08-20 00:12:00 #0 0x5613c952e6ca <unknown>
2024-08-20 00:12:00 #1 0x5613c91ff600 <unknown>
2024-08-20 00:12:00 #2 0x5613c924ebcb <unknown>
2024-08-20 00:12:00 #3 0x5613c924eeb1 <unknown>
2024-08-20 00:12:00 #4 0x5613c9292b24 <unknown>
2024-08-20 00:12:00 #5 0x5613c92718cd <unknown>
2024-08-20 00:12:00 #6 0x5613c929004a <unknown>
2024-08-20 00:12:00 #7 0x5613c9271643 <unknown>
2024-08-20 00:12:00 #8 0x5613c9241d31 <unknown>
2024-08-20 00:12:00 #9 0x5613c924279e <unknown>
2024-08-20 00:12:00 #10 0x5613c94f625b <unknown>
2024-08-20 00:12:00 #11 0x5613c94fa1f2 <unknown>
2024-08-20 00:12:00 #12 0x5613c94e3615 <unknown>
2024-08-20 00:12:00 #13 0x5613c94fad82 <unknown>
2024-08-20 00:12:00 #14 0x5613c94c825f <unknown>
2024-08-20 00:12:00 #15 0x5613c951de68 <unknown>
2024-08-20 00:12:00 #16 0x5613c951e040 <unknown>
2024-08-20 00:12:00 #17 0x5613c952d49c <unknown>
2024-08-20 00:12:00 #18 0x7fd9c2294ac3 <unknown>
2024-08-20 00:12:00 
2024-08-20 00:12:25 2024-08-20 00:12:25 [INFO] [root] [dailySet.py:29] [DAILY SET] Completing search of card 3
```

**Comment by ttraxxrepo** [comment]
Still having issue on https://github.com/klept0/MS-Rewards-Farmer/commit/0a940910abadf68ba413ae0d2325ab7b2958bba7 but with new log

```
2024-08-26 10:12:54 [INFO] [root] [browser.py:142] Screen size: 2157x1554
2024-08-26 10:12:54 [INFO] [root] [browser.py:143] Device size: 2102x1403
2024-08-26 10:13:06 [INFO] [root] [login.py:29] [LOGIN] Logging-in...
2024-08-26 10:13:06 [INFO] [root] [login.py:38] [LOGIN] Entering email...
2024-08-26 10:13:17 [INFO] [root] [login.py:65] [LOGIN] Entering password...
2024-08-26 10:13:35 [INFO] [root] [login.py:31] [LOGIN] Logged-in successfully !
2024-08-26 10:13:38 [INFO] [root] [main.py:239] [POINTS] You have 0.00 points on your account
2024-08-26 10:13:38 [INFO] [root] [dailySet.py:17] [DAILY SET] Trying to complete the Daily Set...
2024-08-26 10:13:48 [INFO] [root] [dailySet.py:29] [DAILY SET] Completing search of card 1
2024-08-26 10:14:00 [INFO] [root] [dailySet.py:45] [DAILY SET] Completing quiz of card 2
2024-08-26 10:14:15 [ERROR] [root] [dailySet.py:83] [DAILY SET] Error Daily Set of card 2
Traceback (most recent call last):
  File "/msrewards/src/dailySet.py", line 47, in completeDailySet
    self.activities.completeQuiz()
  File "/msrewards/src/activities.py", line 48, in completeQuiz
    self.browser.utils.waitUntilVisible(
  File "/msrewards/src/utils.py", line 74, in waitUntilVisible
    return WebDriverWait(self.webdriver, timeToWait).until(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55d8e02ee81a <unknown>
#1 0x55d8dffbce50 <unknown>
#2 0x55d8e000c644 <unknown>
#3 0x55d8e000c931 <unknown>
#4 0x55d8e0052534 <unknown>
#5 0x55d8e00314bd <unknown>
#6 0x55d8e004f9c6 <unknown>
#7 0x55d8e0031233 <unknown>
#8 0x55d8dffff093 <unknown>
#9 0x55d8e000009e <unknown>
#10 0x55d8e02b5a7b <unknown>
#11 0x55d8e02b9a31 <unknown>
#12 0x55d8e02a1645 <unknown>
#13 0x55d8e02ba5a2 <unknown>
#14 0x55d8e028681f <unknown>
#15 0x55d8e02dd618 <unknown>
#16 0x55d8e02dd7e2 <unknown>
#17 0x55d8e02ed60c <unknown>
#18 0x7fcb34c2eac3 <unknown>
all values are hidden
2024-08-26 10:14:21 [INFO] [root] [dailySet.py:29] [DAILY SET] Completing search of card 3
```

**Comment by Kyrela** [comment]
Hi @ttraxxrepo, do you still have this problem with the latest version of the `develop` branch?
